FROM golang:1.26-alpine

# Install build tools + linter
RUN apk add --no-cache git make curl && \
    go install github.com/air-verse/air@latest && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
      | sh -s -- -b /usr/local/bin v1.62.2
      
ARG USERNAME
ARG USERID
RUN adduser --uid ${USERID} -D ${USERNAME}
# Pre-create Go cache directories and give them to your user
RUN mkdir -p /home/${USERNAME}/.cache/go-build && \
    mkdir -p /home/${USERNAME}/go/pkg/mod && \
    chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}

WORKDIR /app
COPY entrypoint.sh ./entrypoint.sh

RUN chown -R ${USERNAME}:${USERNAME} /app
USER ${USERNAME}

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]

# Air = hot reload: watches for .go file changes, recompiles, restarts
CMD ["air", "-c", ".air.toml"]